import type { Property, RoiInputs } from './types';

export const demoProperties: Property[] = [
  {
    id: 'demo-palermo-duplex',
    slug: 'duplex-palermo-hollywood-terraza-parrilla',
    title: 'Duplex premium con terraza en Palermo Hollywood',
    operationType: 'SALE',
    propertyType: 'Departamento',
    status: 'Publicado',
    price: 268000,
    currency: 'USD',
    expenses: 185000,
    city: 'Ciudad Autonoma de Buenos Aires',
    zone: 'Palermo',
    neighborhood: 'Palermo Hollywood',
    address: 'Costa Rica 5900',
    rooms: 4,
    bedrooms: 3,
    bathrooms: 3,
    garages: 1,
    coveredArea: 132,
    totalArea: 168,
    amenities: ['Terraza', 'Parrilla', 'Cochera', 'Baulera', 'Apto credito'],
    description: 'Unidad lista para publicar y vender con ficha profesional, seguimiento de consultas, reserva y documentacion comercial.',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=84',
    featured: true,
    caseStage: 'Reserva en revision',
    documentStage: 'Boleto base generado',
    leadScore: 92,
    daysPublished: 11,
  },
  {
    id: 'demo-nordelta-casa',
    slug: 'casa-nordelta-lago-pileta',
    title: 'Casa al lago con pileta y suite master',
    operationType: 'SALE',
    propertyType: 'Casa',
    status: 'Publicado',
    price: 740000,
    currency: 'USD',
    expenses: 420000,
    city: 'Tigre',
    zone: 'Nordelta',
    neighborhood: 'Los Lagos',
    address: 'Barrio Los Lagos',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 5,
    garages: 2,
    coveredArea: 310,
    totalArea: 780,
    amenities: ['Vista al lago', 'Pileta', 'Seguridad', 'Parrilla', 'Dependencia'],
    description: 'Propiedad de alto valor con seguimiento de interesados, visitas y documentacion de operacion.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=84',
    featured: true,
    caseStage: 'Carpeta comercial abierta',
    documentStage: 'Autorizacion de venta pendiente',
    leadScore: 86,
    daysPublished: 18,
  },
  {
    id: 'demo-belgrano-alquiler',
    slug: 'departamento-belgrano-alquiler-amoblado',
    title: 'Departamento amoblado en Belgrano R',
    operationType: 'RENT',
    propertyType: 'Departamento',
    status: 'Publicado',
    price: 980000,
    currency: 'ARS',
    expenses: 145000,
    city: 'Ciudad Autonoma de Buenos Aires',
    zone: 'Belgrano',
    neighborhood: 'Belgrano R',
    address: 'Superi 1800',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    garages: 1,
    coveredArea: 82,
    totalArea: 90,
    amenities: ['Amoblado', 'Balcón', 'Cochera', 'Mascotas', 'Laundry'],
    description: 'Ficha lista para alquiler, captura de consultas, preseleccion y contrato base editable.',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Contrato en borrador',
    documentStage: 'Contrato alquiler generado',
    leadScore: 78,
    daysPublished: 7,
  },
  {
    id: 'demo-canning-lote',
    slug: 'lote-canning-barrio-privado',
    title: 'Lote interno en barrio privado de Canning',
    operationType: 'SALE',
    propertyType: 'Lote',
    status: 'Publicado',
    price: 69000,
    currency: 'USD',
    city: 'Ezeiza',
    zone: 'Canning',
    neighborhood: 'Barrio Privado',
    address: 'Ruta 58 km 11',
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    garages: 0,
    coveredArea: 0,
    totalArea: 840,
    amenities: ['Seguridad', 'Club house', 'Laguna', 'Servicios', 'Financiacion'],
    description: 'Lote con ficha publica, consultas segmentadas y documentacion de reserva.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Oferta recibida',
    documentStage: 'Reserva preparada',
    leadScore: 74,
    daysPublished: 24,
  },
  {
    id: 'demo-san-isidro-oficina',
    slug: 'oficina-san-isidro-centro-comercial',
    title: 'Oficina corporativa en San Isidro',
    operationType: 'RENT',
    propertyType: 'Oficina',
    status: 'Publicado',
    price: 1800,
    currency: 'USD',
    expenses: 330000,
    city: 'San Isidro',
    zone: 'Centro',
    neighborhood: 'San Isidro',
    address: 'Av. Centenario 900',
    rooms: 5,
    bedrooms: 0,
    bathrooms: 3,
    garages: 2,
    coveredArea: 210,
    totalArea: 210,
    amenities: ['Cochera', 'Seguridad', 'Sala reuniones', 'Aire central', 'Acceso 24h'],
    description: 'Operacion B2B con seguimiento de decisores, visitas y contrato corporativo.',
    imageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Negociacion activa',
    documentStage: 'Contrato corporativo en revision',
    leadScore: 81,
    daysPublished: 15,
  },
  {
    id: 'demo-mar-del-plata-temporario',
    slug: 'departamento-mar-del-plata-temporario-vista-mar',
    title: 'Temporario frente al mar en Playa Grande',
    operationType: 'TEMPORARY_RENT',
    propertyType: 'Departamento',
    status: 'Publicado',
    price: 145000,
    currency: 'ARS',
    city: 'Mar del Plata',
    zone: 'Playa Grande',
    neighborhood: 'Playa Grande',
    address: 'Bv. Maritimo 3200',
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    garages: 1,
    coveredArea: 48,
    totalArea: 55,
    amenities: ['Vista al mar', 'Cochera', 'Amoblado', 'WiFi', 'Check-in digital'],
    description: 'Publicacion temporaria con agenda de disponibilidad, consultas y contrato corto.',
    imageUrl: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Disponibilidad confirmada',
    documentStage: 'Contrato temporario listo',
    leadScore: 69,
    daysPublished: 5,
  },
];

export const defaultRoiInputs: RoiInputs = {
  properties: 65,
  monthlyLeads: 240,
  conversionRate: 1.1,
  averageCommission: 1800,
  adminHoursPerWeek: 22,
  hourlyCost: 12,
};

export const marketInsights = [
  {
    value: '0.4% - 1.2%',
    label: 'conversion promedio de consultas inmobiliarias digitales',
    source: 'RealScout / JustCall, 2026',
  },
  {
    value: '5 min',
    label: 'ventana critica para responder antes que otro agente gane la conversacion',
    source: 'Harvard Business Review citado por RealScout',
  },
  {
    value: '2+ h/dia',
    label: 'tiempo operativo que puede recuperar una inmobiliaria con automatizacion',
    source: 'Meduzzen, 2026',
  },
  {
    value: '30-50%',
    label: 'reduccion potencial de carga administrativa por automatizar flujos repetibles',
    source: 'Epiphany Dynamics, 2026',
  },
];

export const funnelSteps = [
  {
    title: 'Publicar',
    text: 'Carga propiedad, fotos, amenities, precio, estado y ficha compartible con logo de la inmobiliaria.',
  },
  {
    title: 'Captar',
    text: 'El interesado consulta desde ficha publica, WhatsApp o formulario y entra al seguimiento comercial con trazabilidad.',
  },
  {
    title: 'Operar',
    text: 'Se agenda visita, cambia el estado de la consulta y se genera documentacion comercial.',
  },
  {
    title: 'Cerrar',
    text: 'Reserva, autorizacion, boleto o contrato se generan con datos de la operacion y quedan adjuntos.',
  },
];

export const copilotKnowledge = [
  {
    intent: ['sin ia', 'deterministico', 'reglas', 'seguro', 'automatizar'],
    title: 'Copiloto sin IA: operación segura',
    answer: 'Diagnóstico: la inmobiliaria no necesita “chat lindo”, necesita que el sistema opere sin perder control.\n\nQué hace sin IA: busca propiedades, registra consultas, pide datos faltantes, agenda visita, prepara reserva desde plantilla y deja trazabilidad.\n\nRegla comercial: no inventa datos, no cambia estados sensibles y no emite documentos finales sin confirmación.',
  },
  {
    intent: ['ia', 'inteligencia', 'redactar', 'resumir', 'asesor'],
    title: 'Copiloto con IA: asesor comercial',
    answer: 'La IA entra donde hay ambigüedad: interpreta pedidos, resume necesidades, redacta respuestas, arma objeciones y recomienda el siguiente paso.\n\nNo es dueño del flujo: si hay que reservar, cambiar estado, emitir contrato o enviar documentación, deja una propuesta para revisión humana.\n\nAsí se vende: IA para acelerar criterio comercial, no para reemplazar responsabilidad profesional.',
  },
  {
    intent: ['consulta', 'interesado', 'cliente', 'contacto'],
    title: 'Atencion profesional de consultas',
    answer: 'Un lead inmobiliario se enfría rápido. La respuesta profesional no es “te paso fotos”: es confirmar necesidad, presupuesto, zona, urgencia, forma de contacto y disponibilidad para visita.\n\nInmoPub asocia cada consulta a propiedad, fuente, responsable y próxima acción.\n\nSiguiente paso recomendado: proponer dos horarios concretos y dejar la consulta en estado “visita propuesta” o “calificación pendiente”.',
  },
  {
    intent: ['visita', 'mostrar', 'recorrido', 'agenda'],
    title: 'De consulta a visita',
    answer: 'Objetivo: convertir una consulta calificada en visita real.\n\nFlujo recomendado: responder rápido, validar presupuesto, ofrecer dos horarios, confirmar WhatsApp/email y registrar comentarios.\n\nCómo lo vendés: la inmobiliaria deja de depender de memoria y chats sueltos; cada interesado queda con estado, origen, propiedad y responsable.',
  },
  {
    intent: ['tasacion', 'precio', 'valor', 'publicar'],
    title: 'Publicacion y precio',
    answer: 'Una ficha vendible tiene que responder antes de que el usuario pregunte: ubicación, precio, ambientes, superficies, amenities, expensas, fotos claras y beneficios de zona.\n\nSi el precio está en revisión, conviene publicar con estrategia consultiva y medir interés real: búsquedas, aperturas, consultas y visitas.\n\nDato clave para la demo: no mostramos sólo catálogo; mostramos señales comerciales para decidir.',
  },
  {
    intent: ['precio', 'plan', 'cuanto', 'costo'],
    title: 'Suscripcion orientada a resultado',
    answer: 'No lo vendería como “software barato”. Lo vendería como suscripción para ordenar captación, publicación, seguimiento y documentación.\n\nEntrada recomendada: prueba fiel de 3 meses con propiedades reales.\n\nMétricas de decisión: consultas recuperadas, velocidad de respuesta, visitas coordinadas, documentos emitidos y operaciones abiertas. Si mejora, el plan se escala con evidencia.',
  },
  {
    intent: ['demo', 'mostrar', 'presentacion', 'vender'],
    title: 'Demo recomendada',
    answer: 'Demo ganadora en 90 segundos:\n1. Cargar una propiedad con fotos y amenities.\n2. Publicar ficha con logo de la inmobiliaria.\n3. Simular consulta.\n4. Calificar interesado y proponer visita.\n5. Generar reserva o autorización.\n\nCierre: “Probemos 3 meses con tus propiedades, medimos consultas, visitas y documentos, y si resuelve el problema activamos la suscripción”.',
  },
  {
    intent: ['roi', 'retorno', 'conversion', 'vende'],
    title: 'Retorno comercial',
    answer: 'El ROI no está en “tener web”. Está en responder antes, no perder consultas y reducir doble carga.\n\nMedición mínima: consultas, tiempo de respuesta, visitas, documentos emitidos, reservas y operaciones abiertas.\n\nArgumento de venta: si recupera una operación, evita horas administrativas o mejora conversión de leads actuales, la suscripción se defiende sola.',
  },
  {
    intent: ['documento', 'contrato', 'reserva', 'boleto', 'operacion'],
    title: 'Propiedades + documentos',
    answer: 'Documentos que venden confianza: reserva, autorización de venta/alquiler, boleto, contrato base, recibo de seña y entrega de llaves.\n\nEl copiloto puede pedir datos faltantes, previsualizar el documento con logo y datos de la inmobiliaria, y dejarlo listo para revisión.\n\nRegla profesional: nunca emite final ni envía documentación sensible sin confirmación.',
  },
  {
    intent: ['alquiler', 'venta', 'temporario', 'reservar'],
    title: 'Venta, alquiler o temporario',
    answer: 'El producto se adapta por operación:\n\nVenta: reserva, autorización, boleto y negociación.\nAlquiler: perfil del interesado, garantía, contrato y entrega.\nTemporario: disponibilidad, seña, reglas de estadía y check-in.\n\nLa demo debe mostrar que no es un catálogo genérico: cada operación tiene estados, datos y documentos propios.',
  },
  {
    intent: ['objecion', 'objeciones', 'competencia', 'portal', 'zonaprop', 'argenprop', 'mercadolibre'],
    title: 'Como manejar la objecion de portales',
    answer: 'Objeción: “Ya publico en portales”.\n\nRespuesta: perfecto, seguí usándolos. InmoPub no compite por tráfico masivo; ordena lo que pasa después: consulta, seguimiento, visita, reserva y documentación.\n\nPitch: “No reemplazamos portales; evitamos que tus consultas queden perdidas en WhatsApp, planillas y memoria del vendedor”.',
  },
  {
    intent: ['cerrar', 'cierre', 'comprar', 'contratar', 'prueba', '3 meses'],
    title: 'Cierre comercial',
    answer: 'Cierre profesional:\n\n“Tomemos 10 a 30 propiedades reales. Activamos ficha pública, capturamos consultas, usamos estados comerciales y generamos documentos. En 3 meses medimos si mejora respuesta, orden y oportunidades. Si funciona, lo convertimos en suscripción”.\n\nEso baja fricción y evita vender promesas abstractas.',
  },
  {
    intent: ['marketing', 'campana', 'medir', 'ads'],
    title: 'Marketing medible',
    answer: 'La campaña debe medir intención real, no sólo visitas.\n\nEventos útiles: vistas, filtros, propiedades abiertas, simulador ROI, clicks de WhatsApp, consultas y preguntas al copiloto.\n\nEstrategia: segmentar anuncios por dolor. “Pierdo consultas”, “no tengo web propia”, “tardo en responder”, “documentos desordenados” o “quiero captar propietarios”.',
  },
  {
    intent: ['captar', 'propietario', 'captacion', 'tasar'],
    title: 'Captacion de propietarios',
    answer: 'Para captar propietarios, la promesa no es “publico tu inmueble”. Es “te doy una ficha profesional, seguimiento medible, interesados ordenados y documentación lista para avanzar”.\n\nLa landing puede usar un CTA específico: “Quiero evaluar mi propiedad” y el backoffice lo convierte en oportunidad comercial.',
  },
];
