import type { Property, RoiInputs } from './types';

export const demoProperties: Property[] = [
  {
    id: 'demo-palermo-duplex',
    slug: 'duplex-palermo-hollywood-terraza-parrilla',
    title: 'Duplex premium con terraza en Palermo Hollywood',
    operationType: 'SALE',
    propertyType: 'Departamento',
    status: 'Publicado',
    price: 268000,
    currency: 'USD',
    expenses: 185000,
    city: 'Ciudad Autonoma de Buenos Aires',
    zone: 'Palermo',
    neighborhood: 'Palermo Hollywood',
    address: 'Costa Rica 5900',
    rooms: 4,
    bedrooms: 3,
    bathrooms: 3,
    garages: 1,
    coveredArea: 132,
    totalArea: 168,
    amenities: ['Terraza', 'Parrilla', 'Cochera', 'Baulera', 'Apto credito'],
    description: 'Unidad lista para publicar y vender con ficha profesional, seguimiento de consultas, reserva y documentacion comercial.',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=84',
    featured: true,
    caseStage: 'Reserva en revision',
    documentStage: 'Boleto base generado',
    leadScore: 92,
    daysPublished: 11,
  },
  {
    id: 'demo-nordelta-casa',
    slug: 'casa-nordelta-lago-pileta',
    title: 'Casa al lago con pileta y suite master',
    operationType: 'SALE',
    propertyType: 'Casa',
    status: 'Publicado',
    price: 740000,
    currency: 'USD',
    expenses: 420000,
    city: 'Tigre',
    zone: 'Nordelta',
    neighborhood: 'Los Lagos',
    address: 'Barrio Los Lagos',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 5,
    garages: 2,
    coveredArea: 310,
    totalArea: 780,
    amenities: ['Vista al lago', 'Pileta', 'Seguridad', 'Parrilla', 'Dependencia'],
    description: 'Propiedad de alto valor con seguimiento de interesados, visitas y documentacion de operacion.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=84',
    featured: true,
    caseStage: 'Carpeta comercial abierta',
    documentStage: 'Autorizacion de venta pendiente',
    leadScore: 86,
    daysPublished: 18,
  },
  {
    id: 'demo-belgrano-alquiler',
    slug: 'departamento-belgrano-alquiler-amoblado',
    title: 'Departamento amoblado en Belgrano R',
    operationType: 'RENT',
    propertyType: 'Departamento',
    status: 'Publicado',
    price: 980000,
    currency: 'ARS',
    expenses: 145000,
    city: 'Ciudad Autonoma de Buenos Aires',
    zone: 'Belgrano',
    neighborhood: 'Belgrano R',
    address: 'Superi 1800',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    garages: 1,
    coveredArea: 82,
    totalArea: 90,
    amenities: ['Amoblado', 'Balcón', 'Cochera', 'Mascotas', 'Laundry'],
    description: 'Ficha lista para alquiler, captura de consultas, preseleccion y contrato base editable.',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Contrato en borrador',
    documentStage: 'Contrato alquiler generado',
    leadScore: 78,
    daysPublished: 7,
  },
  {
    id: 'demo-canning-lote',
    slug: 'lote-canning-barrio-privado',
    title: 'Lote interno en barrio privado de Canning',
    operationType: 'SALE',
    propertyType: 'Lote',
    status: 'Publicado',
    price: 69000,
    currency: 'USD',
    city: 'Ezeiza',
    zone: 'Canning',
    neighborhood: 'Barrio Privado',
    address: 'Ruta 58 km 11',
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    garages: 0,
    coveredArea: 0,
    totalArea: 840,
    amenities: ['Seguridad', 'Club house', 'Laguna', 'Servicios', 'Financiacion'],
    description: 'Lote con ficha publica, consultas segmentadas y documentacion de reserva.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Oferta recibida',
    documentStage: 'Reserva preparada',
    leadScore: 74,
    daysPublished: 24,
  },
  {
    id: 'demo-san-isidro-oficina',
    slug: 'oficina-san-isidro-centro-comercial',
    title: 'Oficina corporativa en San Isidro',
    operationType: 'RENT',
    propertyType: 'Oficina',
    status: 'Publicado',
    price: 1800,
    currency: 'USD',
    expenses: 330000,
    city: 'San Isidro',
    zone: 'Centro',
    neighborhood: 'San Isidro',
    address: 'Av. Centenario 900',
    rooms: 5,
    bedrooms: 0,
    bathrooms: 3,
    garages: 2,
    coveredArea: 210,
    totalArea: 210,
    amenities: ['Cochera', 'Seguridad', 'Sala reuniones', 'Aire central', 'Acceso 24h'],
    description: 'Operacion B2B con seguimiento de decisores, visitas y contrato corporativo.',
    imageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Negociacion activa',
    documentStage: 'Contrato corporativo en revision',
    leadScore: 81,
    daysPublished: 15,
  },
  {
    id: 'demo-mar-del-plata-temporario',
    slug: 'departamento-mar-del-plata-temporario-vista-mar',
    title: 'Temporario frente al mar en Playa Grande',
    operationType: 'TEMPORARY_RENT',
    propertyType: 'Departamento',
    status: 'Publicado',
    price: 145000,
    currency: 'ARS',
    city: 'Mar del Plata',
    zone: 'Playa Grande',
    neighborhood: 'Playa Grande',
    address: 'Bv. Maritimo 3200',
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    garages: 1,
    coveredArea: 48,
    totalArea: 55,
    amenities: ['Vista al mar', 'Cochera', 'Amoblado', 'WiFi', 'Check-in digital'],
    description: 'Publicacion temporaria con agenda de disponibilidad, consultas y contrato corto.',
    imageUrl: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=84',
    caseStage: 'Disponibilidad confirmada',
    documentStage: 'Contrato temporario listo',
    leadScore: 69,
    daysPublished: 5,
  },
];

export const defaultRoiInputs: RoiInputs = {
  properties: 65,
  monthlyLeads: 240,
  conversionRate: 1.1,
  averageCommission: 1800,
  adminHoursPerWeek: 22,
  hourlyCost: 12,
};

export const marketInsights = [
  {
    value: '0.4% - 1.2%',
    label: 'conversion promedio de consultas inmobiliarias digitales',
    source: 'RealScout / JustCall, 2026',
  },
  {
    value: '5 min',
    label: 'ventana critica para responder antes que otro agente gane la conversacion',
    source: 'Harvard Business Review citado por RealScout',
  },
  {
    value: '2+ h/dia',
    label: 'tiempo operativo que puede recuperar una inmobiliaria con automatizacion',
    source: 'Meduzzen, 2026',
  },
  {
    value: '30-50%',
    label: 'reduccion potencial de carga administrativa por automatizar flujos repetibles',
    source: 'Epiphany Dynamics, 2026',
  },
];

export const funnelSteps = [
  {
    title: 'Publicar',
    text: 'Carga propiedad, fotos, amenities, precio, estado y ficha compartible con logo de la inmobiliaria.',
  },
  {
    title: 'Captar',
    text: 'El interesado consulta desde ficha publica, WhatsApp o formulario y entra al seguimiento comercial con trazabilidad.',
  },
  {
    title: 'Operar',
    text: 'Se agenda visita, cambia el estado de la consulta y se genera documentacion comercial.',
  },
  {
    title: 'Cerrar',
    text: 'Reserva, autorizacion, boleto o contrato se generan con datos de la operacion y quedan adjuntos.',
  },
];

export const copilotKnowledge = [
  {
    intent: ['consulta', 'interesado', 'cliente', 'contacto'],
    title: 'Atencion profesional de consultas',
    answer: 'La mejor respuesta inmobiliaria no es solo mandar fotos: confirmar necesidad, presupuesto, zona, urgencia, forma de contacto y disponibilidad para visita. InmoPub ayuda a que cada consulta quede asociada a una propiedad, con fuente, responsable y siguiente accion.',
  },
  {
    intent: ['visita', 'mostrar', 'recorrido', 'agenda'],
    title: 'De consulta a visita',
    answer: 'Para aumentar cierres, el objetivo es convertir consultas calificadas en visitas concretas. Conviene responder rapido, proponer dos horarios, confirmar datos del interesado y dejar registro de visita, estado y comentarios para seguimiento.',
  },
  {
    intent: ['tasacion', 'precio', 'valor', 'publicar'],
    title: 'Publicacion y precio',
    answer: 'Una ficha vendible debe mostrar ubicacion, precio, ambientes, superficies, amenities, expensas, fotos claras y beneficios de zona. Si el precio esta en revision, se puede publicar con estrategia consultiva y medir consultas para ajustar la propuesta comercial.',
  },
  {
    intent: ['precio', 'plan', 'cuanto', 'costo'],
    title: 'Precio orientado a resultado',
    answer: 'InmoPub se vende mejor como mini portal inmobiliario + seguimiento comercial + documentos. La demo debe mostrar ahorro de horas, velocidad de respuesta y operaciones cerradas, no solo cantidad de propiedades. Para cotizar, conviene mirar cantidad de propiedades activas, usuarios, sucursales/vendedores y volumen de consultas mensual.',
  },
  {
    intent: ['demo', 'mostrar', 'presentacion', 'vender'],
    title: 'Demo recomendada',
    answer: 'La demo ganadora dura 90 segundos: cargar propiedad, publicar ficha, simular consulta, priorizarla, preparar una reserva y generar documento comercial. Ese flujo demuestra valor operativo y comercial sin explicar menus.',
  },
  {
    intent: ['roi', 'retorno', 'conversion', 'vende'],
    title: 'Retorno comercial',
    answer: 'El retorno aparece cuando se responde rapido, no se pierden consultas y se elimina doble carga. Si una inmobiliaria recupera apenas 2 operaciones por mes o evita 20 horas operativas, el software se paga solo. El punto fuerte es medir consultas, tiempos de respuesta, visitas y documentos emitidos.',
  },
  {
    intent: ['documento', 'contrato', 'reserva', 'boleto', 'operacion'],
    title: 'Propiedades + documentos',
    answer: 'Cada operacion puede preparar reserva, autorizacion de venta/alquiler, boleto, contrato, entrega de llaves o documentacion de escribania. El copiloto no guarda sin confirmacion: previsualiza datos, pide faltantes y genera el documento para revisar.',
  },
  {
    intent: ['alquiler', 'venta', 'temporario', 'reservar'],
    title: 'Venta, alquiler o temporario',
    answer: 'InmoPub sirve para venta, alquiler y temporario: la diferencia esta en estados, datos pedidos y documentos. Venta prioriza reserva/autorizacion/boleto; alquiler prioriza perfil del interesado, garantia, contrato y entrega; temporario prioriza disponibilidad, senia y reglas de estadia.',
  },
  {
    intent: ['objecion', 'objeciones', 'competencia', 'portal', 'zonaprop', 'argenprop', 'mercadolibre'],
    title: 'Como manejar la objecion de portales',
    answer: 'InmoPub no compite por trafico masivo contra portales. Se posiciona como mini portal propio + seguimiento + documentos: ordena consultas que llegan por web, WhatsApp, redes o portales y evita que la operacion quede perdida en chats y planillas.',
  },
  {
    intent: ['marketing', 'campana', 'medir', 'ads'],
    title: 'Marketing medible',
    answer: 'La landing mide vistas, filtros, propiedades vistas, simulaciones de retorno, clicks de WhatsApp, consultas y preguntas del copiloto. Eso permite optimizar anuncios por intencion real: venta, alquiler, tasacion, documentacion o demo.',
  },
];
